// @ts-ignore - allow side-effect CSS import without type declarations
import "../globals.css"
import ReduxProvider from "@/redux/reduxProvider"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full antialiased" cz-shortcut-listen="true">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
